<?php

require_once dirname(__FILE__) . '/../../../../../../../codelist.php';

/**
 * Test class for codelist.
 * Generated by PHPUnit on 2012-02-06 at 11:31:33.
 */
class codelistTest extends PHPUnit_Framework_TestCase {

    /**
     * @var codelist
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new codelist;
        
        $con = mysql_connect("localhost","root","");
            if (!$con)
            {
            die('Could not connect: ' . mysql_error());
            }
            
           $sel = mysql_select_db('drupal7');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (4) == 8.
     *
     * @covers codelist::get_nid_by_membership_type
     */
    public function testGet_nid_by_membership_type() {
        $this->assertEquals(8, $this->object->get_nid_by_membership_type(4) );
        $this->assertEquals(4, $this->object->get_nid_by_membership_type(0) );
        $this->assertEquals(11, $this->object->get_nid_by_membership_type(5) );
        $this->assertEquals(13, $this->object->get_nid_by_membership_type(9) );
        
        $print ($this->object->get_nid_by_membership_type(4));
    }

    /**
     * @covers codelist::load
     * @todo Implement testLoad().
     */
    public function testLoad() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers codelist::load_by_id
     * @todo Implement testLoad_by_id().
     */
    public function testLoad_by_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers codelist::get_var_name
     * @todo Implement testGet_var_name().
     */
    public function testGet_var_name() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers codelist::decode
     * @todo Implement testDecode().
     */
    public function testDecode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
